"""initial_safedrive_3_schema

Revision ID: 7e7fd8a7406c
Revises: 
Create Date: 2026-10-05 00:26:49.968710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7fd8a7406c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_datasets_id'), 'evaluation_datasets', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_datasets_name'), 'evaluation_datasets', ['name'], unique=True)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('confusion_matrix', sa.JSON(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('false_negative_rate', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('hardware', sa.String(length=100), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_dataset_id'), 'evaluation_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_id'), 'evaluation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_model_name'), 'evaluation_runs', ['model_name'], unique=False)
    op.create_table('event_graph_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['detection_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['driving_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_graph_nodes_event_id'), 'event_graph_nodes', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_graph_nodes_id'), 'event_graph_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_event_graph_nodes_session_id'), 'event_graph_nodes', ['session_id'], unique=False)
    op.create_index(op.f('ix_event_graph_nodes_timestamp'), 'event_graph_nodes', ['timestamp'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['detection_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['driving_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_evidence_records_created_at'), 'evidence_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_records_event_id'), 'evidence_records', ['event_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_id'), 'evidence_records', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_records_retention_expires_at'), 'evidence_records', ['retention_expires_at'], unique=False)
    op.create_index(op.f('ix_evidence_records_session_id'), 'evidence_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_sha256'), 'evidence_records', ['sha256'], unique=False)
    op.create_table('event_graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('time_delta_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['driving_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['event_graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['event_graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_graph_edges_id'), 'event_graph_edges', ['id'], unique=False)
    op.create_index(op.f('ix_event_graph_edges_session_id'), 'event_graph_edges', ['session_id'], unique=False)
    op.create_index(op.f('ix_event_graph_edges_source_node_id'), 'event_graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_event_graph_edges_target_node_id'), 'event_graph_edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_graph_edges_target_node_id'), table_name='event_graph_edges')
    op.drop_index(op.f('ix_event_graph_edges_source_node_id'), table_name='event_graph_edges')
    op.drop_index(op.f('ix_event_graph_edges_session_id'), table_name='event_graph_edges')
    op.drop_index(op.f('ix_event_graph_edges_id'), table_name='event_graph_edges')
    op.drop_table('event_graph_edges')
    op.drop_index(op.f('ix_evidence_records_sha256'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_session_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_retention_expires_at'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_event_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_created_at'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_event_graph_nodes_timestamp'), table_name='event_graph_nodes')
    op.drop_index(op.f('ix_event_graph_nodes_session_id'), table_name='event_graph_nodes')
    op.drop_index(op.f('ix_event_graph_nodes_id'), table_name='event_graph_nodes')
    op.drop_index(op.f('ix_event_graph_nodes_event_id'), table_name='event_graph_nodes')
    op.drop_table('event_graph_nodes')
    op.drop_index(op.f('ix_evaluation_runs_model_name'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_dataset_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_evaluation_datasets_name'), table_name='evaluation_datasets')
    op.drop_index(op.f('ix_evaluation_datasets_id'), table_name='evaluation_datasets')
    op.drop_table('evaluation_datasets')
    # ### end Alembic commands ###
